import type { SeedWordPart } from "./types";

/** 60 high-utility SAT roots, part 2 of 2 (nov — volv/volu). */
export const ROOTS_2: SeedWordPart[] = [
  {
    text: "nov",
    type: "root",
    meaning: "new",
    description: "Nov means “new.” A novel is new; a novice is new at something.",
    origin: "Latin",
    difficulty: "beginner",
    category: "time",
    mnemonic: "Novel — new.",
    related: ["re-", "neo"],
    words: [
      { word: "novel", definition: "new; also, a long work of fiction", sentence: "She wrote a novel." },
      { word: "novice", definition: "a beginner", sentence: "He is a novice at chess." },
      { word: "renovate", definition: "to make new again", sentence: "They renovated the old kitchen." },
      { word: "innovate", definition: "to make new", sentence: "The company innovates every year." },
      { word: "nova", definition: "a newly bright star", sentence: "A nova brightened in the sky." },
    ],
  },
  {
    text: "path",
    type: "root",
    meaning: "feel; suffer",
    description: "Path means “feel” or “suffer.” Sympathy is feeling together with someone.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "mind",
    mnemonic: "Sympathy — feeling together.",
    related: ["sent/sens"],
    words: [
      { word: "sympathy", definition: "feeling together with someone", sentence: "She sent her sympathy." },
      { word: "empathy", definition: "feeling as another feels", sentence: "Empathy requires imagination." },
      { word: "apathy", definition: "without feeling", sentence: "Apathy spread through the crowd." },
      { word: "pathetic", definition: "arousing pity", sentence: "The excuse was pathetic." },
      { word: "pathology", definition: "the study of disease and suffering", sentence: "Pathology revealed the cause." },
    ],
  },
  {
    text: "ped/pod",
    type: "root",
    meaning: "foot",
    description: "Ped/pod means “foot.” A pedestrian goes on foot.",
    origin: "Greek/Latin",
    difficulty: "beginner",
    category: "body",
    mnemonic: "Pedal — a foot lever.",
    related: ["man/manu"],
    words: [
      { word: "pedal", definition: "a foot-operated lever", sentence: "Press the pedal to start." },
      { word: "pedestrian", definition: "one who goes on foot", sentence: "Pedestrians use the crosswalk." },
      { word: "podiatrist", definition: "a foot doctor", sentence: "The podiatrist treated her heel." },
      { word: "tripod", definition: "a three-footed stand", sentence: "Mount the camera on the tripod." },
      { word: "impede", definition: "to slow the foot — to block", sentence: "The snow impeded our progress." },
    ],
  },
  {
    text: "pel/puls",
    type: "root",
    meaning: "drive; push",
    description: "Pel/puls means “drive” or “push.” To propel is to push forward.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Propel — push forward.",
    related: ["ject", "duc/duct"],
    words: [
      { word: "propel", definition: "to push forward", sentence: "The engine propels the boat." },
      { word: "repel", definition: "to push back", sentence: "The spray repels insects." },
      { word: "expel", definition: "to push out", sentence: "The school expelled him." },
      { word: "impulse", definition: "a sudden push to act", sentence: "She bought it on impulse." },
      { word: "compel", definition: "to push strongly — to force", sentence: "The law compels obedience." },
    ],
  },
  {
    text: "pend/pens",
    type: "root",
    meaning: "hang; weigh",
    description: "Pend/pens means “hang” or “weigh.” A pending question hangs unresolved.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "quality",
    mnemonic: "Suspend — hang up.",
    related: ["equ", "sta/stat/stan"],
    words: [
      { word: "pending", definition: "hanging — undecided", sentence: "The decision is still pending." },
      { word: "suspend", definition: "to hang", sentence: "Suspend the lamp from the ceiling." },
      { word: "pendulum", definition: "a hanging weight that swings", sentence: "The pendulum swung steadily." },
      { word: "compensate", definition: "to weigh together — to pay back", sentence: "The company compensated her for the loss." },
      { word: "expensive", definition: "weighed out — costly", sentence: "The dress was expensive." },
    ],
  },
  {
    text: "phon",
    type: "root",
    meaning: "sound",
    description: "Phon means “sound.” A telephone carries sound far away.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "perception",
    mnemonic: "Telephone — sound from far.",
    related: ["aud"],
    words: [
      { word: "telephone", definition: "an instrument that carries sound far", sentence: "The telephone rang at midnight." },
      { word: "phonics", definition: "teaching reading through sounds", sentence: "Phonics helps children learn to read." },
      { word: "symphony", definition: "a sounding together", sentence: "The symphony thrilled the audience." },
      { word: "microphone", definition: "makes small sound big", sentence: "Speak into the microphone." },
      { word: "cacophony", definition: "harsh, clashing sound", sentence: "The traffic was a cacophony." },
    ],
  },
  {
    text: "port",
    type: "root",
    meaning: "carry",
    description: "Port means “carry.” Something portable can be carried.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Portable — able to be carried.",
    related: ["fer", "duc/duct"],
    words: [
      { word: "portable", definition: "able to be carried", sentence: "She bought a portable charger." },
      { word: "transport", definition: "to carry across", sentence: "The port transports goods by ship." },
      { word: "export", definition: "to carry out", sentence: "The country exports coffee." },
      { word: "import", definition: "to carry in", sentence: "We import most of our cars." },
      { word: "report", definition: "to carry back news", sentence: "Report your findings to the team." },
      { word: "support", definition: "to carry from below", sentence: "The beams support the roof." },
    ],
  },
  {
    text: "pos/pon/pound",
    type: "root",
    meaning: "place; put",
    description: "Pos/pon/pound means “place” or “put.” To compose is to put together.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Position — a place.",
    related: ["struct", "fac/fact/fect"],
    words: [
      { word: "position", definition: "a place", sentence: "Take your position at the start line." },
      { word: "compose", definition: "to put together", sentence: "She composed a symphony." },
      { word: "deposit", definition: "to put down", sentence: "Deposit the check at the bank." },
      { word: "opponent", definition: "one put against you", sentence: "Her opponent conceded the match." },
      { word: "postpone", definition: "to put after", sentence: "They postponed the meeting." },
    ],
  },
  {
    text: "prim",
    type: "root",
    meaning: "first",
    description: "Prim means “first.” The primary concern is the first concern.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "time",
    mnemonic: "Primary — first.",
    related: ["pre-", "proto"],
    words: [
      { word: "primary", definition: "first in importance", sentence: "Safety is the primary concern." },
      { word: "primitive", definition: "of the first kind — early", sentence: "The tool was primitive but effective." },
      { word: "prime", definition: "first in quality", sentence: "She is in her prime." },
      { word: "primal", definition: "first, original", sentence: "Fear is a primal emotion." },
    ],
  },
  {
    text: "rupt",
    type: "root",
    meaning: "break",
    description: "Rupt means “break.” To erupt is to break out.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Erupt — break out.",
    related: ["fract/frag"],
    words: [
      { word: "erupt", definition: "to break out", sentence: "The volcano erupted at dawn." },
      { word: "interrupt", definition: "to break in", sentence: "Please don't interrupt." },
      { word: "disrupt", definition: "to break apart", sentence: "The storm disrupted the power." },
      { word: "rupture", definition: "a break", sentence: "The pipe ruptured underground." },
      { word: "bankrupt", definition: "broken of money", sentence: "The company went bankrupt." },
    ],
  },
  {
    text: "scrib/script",
    type: "root",
    meaning: "write",
    description: "Scrib/script means “write.” To describe is to write down.",
    origin: "Latin",
    difficulty: "beginner",
    category: "communication",
    mnemonic: "Describe — write down.",
    related: ["graph/gram", "log/logue"],
    words: [
      { word: "describe", definition: "to write down in detail", sentence: "Describe the suspect to the police." },
      { word: "prescribe", definition: "to write before — order", sentence: "The doctor prescribed rest." },
      { word: "subscribe", definition: "to write under — sign up", sentence: "Subscribe to the magazine." },
      { word: "manuscript", definition: "a hand-written text", sentence: "The manuscript was finally published." },
      { word: "inscribe", definition: "to write in", sentence: "The trophy was inscribed with her name." },
    ],
  },
  {
    text: "sent/sens",
    type: "root",
    meaning: "feel",
    description: "Sent/sens means “feel.” A sensitive person feels deeply.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "mind",
    mnemonic: "Sensitive — feels much.",
    related: ["path"],
    words: [
      { word: "sensible", definition: "showing good sense", sentence: "That's a sensible plan." },
      { word: "sensitive", definition: "feeling deeply", sentence: "He is sensitive to criticism." },
      { word: "sentiment", definition: "a feeling", sentence: "Sentiment ran high after the speech." },
      { word: "sensation", definition: "a feeling or perception", sentence: "The news caused a sensation." },
      { word: "consensus", definition: "a feeling together — agreement", sentence: "The group reached a consensus." },
    ],
  },
  {
    text: "sequ/sec",
    type: "root",
    meaning: "follow",
    description: "Sequ/sec means “follow.” A sequence is an order of following.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Sequel — follows the first.",
    related: ["ced/ceed/cess"],
    words: [
      { word: "sequence", definition: "an order of following", sentence: "Name the sequence of events." },
      { word: "sequel", definition: "that which follows", sentence: "The sequel was better than the original." },
      { word: "consequence", definition: "that which follows", sentence: "Every action has a consequence." },
      { word: "consecutive", definition: "following in order", sentence: "They won three consecutive games." },
      { word: "prosecute", definition: "to follow after in law", sentence: "The state prosecuted the case." },
    ],
  },
  {
    text: "spec/spic",
    type: "root",
    meaning: "look",
    description: "Spec/spic means “look.” To inspect is to look into.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "perception",
    mnemonic: "Spectator — one who looks.",
    related: ["vid/vis"],
    words: [
      { word: "inspect", definition: "to look into", sentence: "Inspect the tires before the trip." },
      { word: "spectator", definition: "one who looks", sentence: "The spectators cheered wildly." },
      { word: "retrospect", definition: "a looking back", sentence: "In retrospect, it was a good decision." },
      { word: "conspicuous", definition: "easily seen — standing out", sentence: "Her red hat was conspicuous." },
      { word: "speculate", definition: "to look at and guess", sentence: "We can only speculate about the cause." },
    ],
  },
  {
    text: "spir",
    type: "root",
    meaning: "breathe",
    description: "Spir means “breathe.” Spirit is breath or soul.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "life",
    mnemonic: "Inspire — breathe into.",
    related: ["bio", "vit/viv"],
    words: [
      { word: "inspire", definition: "to breathe into", sentence: "Her speech inspired the students." },
      { word: "respiration", definition: "breathing", sentence: "Respiration supplies the body with oxygen." },
      { word: "perspire", definition: "to breathe through the skin — sweat", sentence: "He began to perspire under the lights." },
      { word: "spirit", definition: "breath; soul", sentence: "Team spirit won the game." },
      { word: "conspiracy", definition: "a breathing together — a secret plot", sentence: "They were charged with conspiracy." },
    ],
  },
  {
    text: "sta/stat/stan",
    type: "root",
    meaning: "stand",
    description: "Sta/stat/stan means “stand.” A statue stands still.",
    origin: "Latin",
    difficulty: "beginner",
    category: "position",
    mnemonic: "Statue — a standing figure.",
    related: ["pos/pon/pound", "sist"],
    words: [
      { word: "statue", definition: "a standing figure", sentence: "The statue stood in the square." },
      { word: "status", definition: "standing — social position", sentence: "Her status rose quickly." },
      { word: "stable", definition: "standing firm", sentence: "The economy is stable." },
      { word: "station", definition: "a standing place", sentence: "The train reached the station." },
      { word: "obstacle", definition: "that which stands against", sentence: "Remove the obstacle from the path." },
      { word: "constant", definition: "standing with — unchanging", sentence: "She was a constant friend." },
    ],
  },
  {
    text: "struct",
    type: "root",
    meaning: "build",
    description: "Struct means “build.” A structure is something built.",
    origin: "Latin",
    difficulty: "beginner",
    category: "action",
    mnemonic: "Construct — build.",
    related: ["fac/fact/fect"],
    words: [
      { word: "construct", definition: "to build", sentence: "They construct houses in the suburbs." },
      { word: "structure", definition: "a building — what is built", sentence: "The structure was sound." },
      { word: "instruct", definition: "to build in — to teach", sentence: "She instructs yoga on weekends." },
      { word: "destruction", definition: "a breaking down", sentence: "The storm caused widespread destruction." },
      { word: "infrastructure", definition: "the underlying build", sentence: "The city's infrastructure is aging." },
    ],
  },
  {
    text: "tact/tag/tang",
    type: "root",
    meaning: "touch",
    description: "Tact/tag/tang means “touch.” Contact is a touching together.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "perception",
    mnemonic: "Contact — touching together.",
    related: ["path"],
    words: [
      { word: "contact", definition: "a touching", sentence: "Make eye contact when you speak." },
      { word: "intact", definition: "not touched — whole", sentence: "The vase arrived intact." },
      { word: "tactile", definition: "relating to touch", sentence: "The museum exhibit was tactile." },
      { word: "contagious", definition: "spread by touch", sentence: "Laughter is contagious." },
      { word: "tangible", definition: "able to be touched", sentence: "We need tangible results." },
    ],
  },
  {
    text: "ten/tin/tent",
    type: "root",
    meaning: "hold",
    description: "Ten/tin/tent means “hold.” To contain is to hold in.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Contain — hold in.",
    related: ["fer"],
    words: [
      { word: "contain", definition: "to hold in", sentence: "The box contains old books." },
      { word: "maintain", definition: "to hold up — keep", sentence: "Maintain your speed." },
      { word: "tenant", definition: "one who holds land — a renter", sentence: "The tenant paid the rent." },
      { word: "tenacious", definition: "holding firm", sentence: "She was tenacious in pursuit of the truth." },
      { word: "content", definition: "held within; satisfied", sentence: "He is content with his work." },
      { word: "retain", definition: "to hold back — keep", sentence: "Retain the receipt for your records." },
    ],
  },
  {
    text: "terr",
    type: "root",
    meaning: "earth; land",
    description: "Terr means “earth” or “land.” Territory is land under rule.",
    origin: "Latin",
    difficulty: "beginner",
    category: "nature",
    mnemonic: "Territory — land.",
    related: ["geo"],
    words: [
      { word: "territory", definition: "land under rule", sentence: "The cat defended its territory." },
      { word: "terrain", definition: "land features", sentence: "The terrain was rocky and steep." },
      { word: "extraterrestrial", definition: "beyond earth", sentence: "The film shows extraterrestrial life." },
      { word: "Mediterranean", definition: "the sea in the middle of the land", sentence: "The Mediterranean coast is warm." },
      { word: "terrace", definition: "a raised platform of earth", sentence: "They grew tomatoes on the terrace." },
    ],
  },
  {
    text: "therm",
    type: "root",
    meaning: "heat",
    description: "Therm means “heat.” A thermometer measures heat.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "nature",
    mnemonic: "Thermometer — measures heat.",
    related: ["calor", "ign"],
    words: [
      { word: "thermal", definition: "relating to heat", sentence: "Thermal energy is heat energy." },
      { word: "thermometer", definition: "a heat measurer", sentence: "The thermometer read 90 degrees." },
      { word: "thermostat", definition: "keeps heat steady", sentence: "Set the thermostat to 70." },
      { word: "hypothermia", definition: "low body heat", sentence: "Hypothermia is a medical emergency." },
      { word: "geothermal", definition: "heat from the earth", sentence: "Iceland uses geothermal power." },
    ],
  },
  {
    text: "tort",
    type: "root",
    meaning: "twist",
    description: "Tort means “twist.” To distort is to twist out of shape.",
    origin: "Latin",
    difficulty: "advanced",
    category: "action",
    mnemonic: "Distort — twist the truth.",
    related: ["vers/vert"],
    words: [
      { word: "torture", definition: "twisting to cause pain", sentence: "Torture is illegal under any circumstance." },
      { word: "distort", definition: "to twist the truth", sentence: "Don't distort the facts." },
      { word: "contort", definition: "to twist together", sentence: "The dancer contorted her body." },
      { word: "retort", definition: "to twist back a reply", sentence: "She had a quick retort." },
      { word: "tortuous", definition: "full of twists", sentence: "The mountain path was tortuous." },
    ],
  },
  {
    text: "tract",
    type: "root",
    meaning: "pull; drag",
    description: "Tract means “pull” or “drag.” A tractor pulls heavy loads.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Tractor — pulls.",
    related: ["duc/duct", "fer"],
    words: [
      { word: "tractor", definition: "a machine that pulls", sentence: "The tractor plowed the field." },
      { word: "attract", definition: "to pull toward", sentence: "Lights attract insects at night." },
      { word: "subtract", definition: "to pull under — take away", sentence: "Subtract five from ten." },
      { word: "extract", definition: "to pull out", sentence: "They extract vanilla from beans." },
      { word: "contract", definition: "to pull together", sentence: "The muscle contracts when it flexes." },
      { word: "distract", definition: "to pull away", sentence: "The noise distracted me." },
    ],
  },
  {
    text: "vac",
    type: "root",
    meaning: "empty",
    description: "Vac means “empty.” A vacuum is an empty space.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "space",
    mnemonic: "Vacant — empty.",
    related: ["plen"],
    words: [
      { word: "vacant", definition: "empty", sentence: "The seat is vacant." },
      { word: "vacuum", definition: "an empty space", sentence: "Outer space is a vacuum." },
      { word: "evacuate", definition: "to empty out", sentence: "Evacuate the building immediately." },
      { word: "vacation", definition: "a time emptied of work", sentence: "We took a vacation in July." },
      { word: "vacuous", definition: "empty of meaning", sentence: "The speech was vacuous." },
    ],
  },
  {
    text: "ven/vent",
    type: "root",
    meaning: "come",
    description: "Ven/vent means “come.” An event is something that comes to pass.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Adventure — a coming to.",
    related: ["ced/ceed/cess"],
    words: [
      { word: "venture", definition: "a coming forth — a risky undertaking", sentence: "They started a joint venture." },
      { word: "convention", definition: "a coming together", sentence: "The convention gathered thousands." },
      { word: "invent", definition: "to come upon", sentence: "She invented a new device." },
      { word: "prevent", definition: "to come before — stop", sentence: "Prevent the accident before it happens." },
      { word: "event", definition: "that which comes out — occurrence", sentence: "The event was postponed." },
      { word: "adventure", definition: "a coming to — an exciting experience", sentence: "Their adventure began in the mountains." },
    ],
  },
  {
    text: "ver",
    type: "root",
    meaning: "true",
    description: "Ver means “true.” To verify is to make true.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "quality",
    mnemonic: "Verify — make true.",
    related: ["cred", "fid"],
    words: [
      { word: "verify", definition: "to make true — confirm", sentence: "Verify your password to continue." },
      { word: "verdict", definition: "a true saying — a judgment", sentence: "The verdict was guilty." },
      { word: "veracity", definition: "truthfulness", sentence: "He questioned her veracity." },
      { word: "very", definition: "truly", sentence: "Very good, indeed." },
      { word: "aver", definition: "to declare true", sentence: "He averred his innocence." },
    ],
  },
  {
    text: "verb",
    type: "root",
    meaning: "word",
    description: "Verb means “word.” A verb is a doing word.",
    origin: "Latin",
    difficulty: "beginner",
    category: "communication",
    mnemonic: "Verbal — in words.",
    related: ["log/logue", "dict"],
    words: [
      { word: "verbal", definition: "in words", sentence: "She gave verbal consent." },
      { word: "verbatim", definition: "word for word", sentence: "Quote the passage verbatim." },
      { word: "proverb", definition: "a wise saying", sentence: "The proverb says, “Honesty is the best policy.”" },
      { word: "verbose", definition: "full of words", sentence: "The report was verbose and unclear." },
      { word: "adverb", definition: "a word added to a verb", sentence: "An adverb modifies a verb." },
    ],
  },
  {
    text: "vers/vert",
    type: "root",
    meaning: "turn",
    description: "Vers/vert means “turn.” To reverse is to turn back.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Reverse — turn back.",
    related: ["volv/volu", "tort"],
    words: [
      { word: "reverse", definition: "to turn back", sentence: "Reverse the car out of the driveway." },
      { word: "convert", definition: "to turn with — change", sentence: "Convert the file to PDF." },
      { word: "invert", definition: "to turn upside down", sentence: "Invert the image." },
      { word: "universe", definition: "one turn — everything together", sentence: "The universe is vast." },
      { word: "versatile", definition: "able to turn to many uses", sentence: "She is a versatile musician." },
      { word: "version", definition: "a turning — a variant", sentence: "Read the new version of the text." },
    ],
  },
  {
    text: "vid/vis",
    type: "root",
    meaning: "see",
    description: "Vid/vis means “see.” Video is made for seeing.",
    origin: "Latin",
    difficulty: "beginner",
    category: "perception",
    mnemonic: "Vision — sight.",
    related: ["spec/spic", "luc/lum/lus"],
    words: [
      { word: "video", definition: "a recording to be seen", sentence: "Watch the video before class." },
      { word: "vision", definition: "sight", sentence: "She lost her vision in the accident." },
      { word: "visible", definition: "able to be seen", sentence: "The stain is clearly visible." },
      { word: "invisible", definition: "not able to be seen", sentence: "Air is invisible." },
      { word: "evidence", definition: "that which is seen — proof", sentence: "The evidence was clear." },
      { word: "supervise", definition: "to see over — oversee", sentence: "She supervises the team." },
    ],
  },
  {
    text: "vit/viv",
    type: "root",
    meaning: "live; life",
    description: "Vit/viv means “live” or “life.” Something vital is needed for life.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "life",
    mnemonic: "Vital — necessary for life.",
    related: ["bio", "gen"],
    words: [
      { word: "vital", definition: "necessary for life", sentence: "Water is vital for survival." },
      { word: "vitamin", definition: "a substance needed for life", sentence: "Take a vitamin each morning." },
      { word: "revive", definition: "to bring back to life", sentence: "The cold water revived her." },
      { word: "survive", definition: "to live through", sentence: "She survived the crash." },
      { word: "vivid", definition: "lively, lifelike", sentence: "The dream was vivid." },
      { word: "vivacious", definition: "full of life", sentence: "She is vivacious and outgoing." },
    ],
  },
  {
    text: "ced/ceed/cess",
    type: "root",
    meaning: "go; yield",
    description: "Ced/ceed/cess means “go” or “yield.” To proceed is to go forward.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Proceed — go forward.",
    related: ["grad/gress", "mot/mov/mob"],
    words: [
      { word: "proceed", definition: "to go forward", sentence: "Proceed with caution." },
      { word: "recede", definition: "to go back", sentence: "The floodwater began to recede." },
      { word: "access", definition: "a going to", sentence: "We gained access to the building." },
      { word: "succeed", definition: "to go under and come up — triumph", sentence: "She succeeded against the odds." },
      { word: "incessant", definition: "not stopping — going on", sentence: "The rain was incessant." },
    ],
  },
  {
    text: "volv/volu",
    type: "root",
    meaning: "roll; turn",
    description: "Volv/volu means “roll” or “turn.” To revolve is to roll around.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Revolve — roll around.",
    related: ["vers/vert"],
    words: [
      { word: "revolve", definition: "to roll around", sentence: "The earth revolves around the sun." },
      { word: "evolve", definition: "to roll forth — develop", sentence: "Species evolve over time." },
      { word: "involve", definition: "to roll in — include", sentence: "The job involves travel." },
      { word: "revolt", definition: "to roll against", sentence: "The people revolted against the crown." },
      { word: "volume", definition: "a rolled scroll — also, loudness", sentence: "Turn up the volume." },
      { word: "devolve", definition: "to roll down — pass to a lower level", sentence: "Power devolved to the states." },
    ],
  },
];
