import type { SeedWordPart } from "./types";

/** 60 high-utility SAT roots, part 1 of 2 (aud — nomen). */
export const ROOTS_1: SeedWordPart[] = [
  {
    text: "aud",
    type: "root",
    meaning: "hear",
    description: "Aud means “hear.” An audience is a group that hears a performance.",
    origin: "Latin",
    difficulty: "beginner",
    category: "perception",
    mnemonic: "Audio — what you hear.",
    related: ["phon", "dict"],
    words: [
      { word: "audience", definition: "a group that hears", sentence: "The audience applauded loudly." },
      { word: "audible", definition: "able to be heard", sentence: "Her whisper was barely audible." },
      { word: "inaudible", definition: "not able to be heard", sentence: "The speaker was inaudible over the noise." },
    ],
  },
  {
    text: "bio",
    type: "root",
    meaning: "life",
    description: "Bio means “life.” Biology is the study of life.",
    origin: "Greek",
    difficulty: "beginner",
    category: "life",
    mnemonic: "Biology — the study of life.",
    related: ["vit/viv", "gen"],
    words: [
      { word: "biology", definition: "the study of life", sentence: "She majors in biology." },
      { word: "biography", definition: "a written account of a life", sentence: "He read a biography of Lincoln." },
      { word: "antibiotic", definition: "a medicine that works against bacteria", sentence: "The antibiotic saved her life." },
    ],
  },
  {
    text: "chron",
    type: "root",
    meaning: "time",
    description: "Chron means “time.” A chronicle records events in time order.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "time",
    mnemonic: "Chronological — in time order.",
    related: ["pre-", "post-"],
    words: [
      { word: "chronological", definition: "in time order", sentence: "Put the events in chronological order." },
      { word: "chronic", definition: "lasting a long time", sentence: "He suffers from chronic pain." },
      { word: "synchronize", definition: "to set at the same time", sentence: "Synchronize your watches." },
    ],
  },
  {
    text: "cred",
    type: "root",
    meaning: "believe",
    description: "Cred means “believe.” A credible source is believable.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "mind",
    mnemonic: "Credit — trust given to someone.",
    related: ["fid", "ver"],
    words: [
      { word: "credible", definition: "believable", sentence: "The witness seemed credible." },
      { word: "incredible", definition: "not believable", sentence: "The view was incredible." },
      { word: "incredulous", definition: "not believing", sentence: "She was incredulous at the news." },
      { word: "credential", definition: "proof of belief in someone's ability", sentence: "The job requires a credential." },
    ],
  },
  {
    text: "dict",
    type: "root",
    meaning: "say; speak",
    description: "Dict means “say.” To dictate is to say words for another to write.",
    origin: "Latin",
    difficulty: "beginner",
    category: "communication",
    mnemonic: "Predict — say before.",
    related: ["log/logue", "verb", "scrib/script"],
    words: [
      { word: "dictate", definition: "to say aloud for writing", sentence: "He dictated a letter to his secretary." },
      { word: "predict", definition: "to say before it happens", sentence: "Scientists predict the storm's path." },
      { word: "contradict", definition: "to say against", sentence: "Don't contradict your supervisor." },
      { word: "verdict", definition: "a spoken judgment", sentence: "The jury returned a verdict." },
    ],
  },
  {
    text: "duc/duct",
    type: "root",
    meaning: "lead",
    description: "Duc/duct means “lead.” A conductor leads an orchestra.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Introduce — lead in.",
    related: ["port", "fer"],
    words: [
      { word: "conduct", definition: "to lead", sentence: "She will conduct the orchestra." },
      { word: "introduce", definition: "to lead in", sentence: "Let me introduce our guest speaker." },
      { word: "produce", definition: "to lead forth", sentence: "The farm produces fresh milk." },
      { word: "deduce", definition: "to lead down from evidence", sentence: "We can deduce the answer from the clues." },
    ],
  },
  {
    text: "equ",
    type: "root",
    meaning: "equal",
    description: "Equ means “equal.” An equation sets two things equal.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "quality",
    mnemonic: "Equal — the same.",
    related: ["ver", "fid"],
    words: [
      { word: "equal", definition: "the same in value", sentence: "All votes are equal." },
      { word: "equation", definition: "a statement of equality", sentence: "Solve the equation for x." },
      { word: "equivalent", definition: "equal in value", sentence: "The two offers are equivalent." },
      { word: "equilibrium", definition: "a balanced state", sentence: "The market found equilibrium." },
    ],
  },
  {
    text: "fac/fact/fect",
    type: "root",
    meaning: "make; do",
    description: "Fac/fact/fect means “make” or “do.” A factory makes things.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Factory — a place that makes.",
    related: ["struct", "gen"],
    words: [
      { word: "factory", definition: "a place that makes goods", sentence: "She works at a chocolate factory." },
      { word: "manufacture", definition: "to make by hand or machine", sentence: "The company manufactures cars." },
      { word: "effect", definition: "a result that is made", sentence: "The medicine had an immediate effect." },
      { word: "defect", definition: "a flaw made in something", sentence: "The product had a serious defect." },
      { word: "facilitate", definition: "to make easy", sentence: "The new app facilitates learning." },
    ],
  },
  {
    text: "fer",
    type: "root",
    meaning: "carry; bear",
    description: "Fer means “carry” or “bear.” A ferry carries people across water.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Transfer — carry across.",
    related: ["port", "duc/duct"],
    words: [
      { word: "transfer", definition: "to carry across", sentence: "Transfer the money to savings." },
      { word: "ferry", definition: "a boat that carries people", sentence: "The ferry crossed the river." },
      { word: "conifer", definition: "a tree that bears cones", sentence: "The pine is a conifer." },
      { word: "aquifer", definition: "an underground layer that bears water", sentence: "The well taps into the aquifer." },
    ],
  },
  {
    text: "fid",
    type: "root",
    meaning: "trust; faith",
    description: "Fid means “trust” or “faith.” Fidelity is faithfulness.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "mind",
    mnemonic: "Confident — full of trust.",
    related: ["cred"],
    words: [
      { word: "fidelity", definition: "faithfulness", sentence: "She valued fidelity above all." },
      { word: "confident", definition: "full of trust in oneself", sentence: "He felt confident before the interview." },
      { word: "infidel", definition: "one without faith", sentence: "The traitor was branded an infidel." },
      { word: "perfidy", definition: "breaking of faith", sentence: "His perfidy shocked everyone." },
    ],
  },
  {
    text: "flu/flux",
    type: "root",
    meaning: "flow",
    description: "Flu/flux means “flow.” Fluid flows; influence flows into us.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Fluid — flows.",
    related: ["cur", "nav"],
    words: [
      { word: "fluid", definition: "a flowing substance", sentence: "Drink plenty of fluid when sick." },
      { word: "influence", definition: "a flowing in of power", sentence: "Her influence grew over the years." },
      { word: "affluent", definition: "flowing with wealth", sentence: "The affluent suburb prospered." },
      { word: "fluctuate", definition: "to flow up and down", sentence: "Prices fluctuate daily." },
    ],
  },
  {
    text: "form",
    type: "root",
    meaning: "shape",
    description: "Form means “shape.” To transform is to change shape.",
    origin: "Latin",
    difficulty: "beginner",
    category: "quality",
    mnemonic: "Transform — change shape.",
    related: ["struct"],
    words: [
      { word: "transform", definition: "to change shape", sentence: "The caterpillar transforms into a butterfly." },
      { word: "uniform", definition: "one shape for all", sentence: "The soldiers wore uniforms." },
      { word: "formula", definition: "a set form or rule", sentence: "The formula for water is H2O." },
      { word: "deform", definition: "to change shape badly", sentence: "The heat deformed the plastic." },
    ],
  },
  {
    text: "fract/frag",
    type: "root",
    meaning: "break",
    description: "Fract/frag means “break.” A fracture is a break in a bone.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "action",
    mnemonic: "Fragile — easily broken.",
    related: ["rupt"],
    words: [
      { word: "fracture", definition: "a break", sentence: "He fractured his wrist playing tennis." },
      { word: "fragment", definition: "a broken piece", sentence: "A fragment of glass remained in the frame." },
      { word: "fragile", definition: "easily broken", sentence: "Handle the vase carefully — it's fragile." },
      { word: "infraction", definition: "a breaking of a rule", sentence: "The infraction cost him a fine." },
    ],
  },
  {
    text: "gen",
    type: "root",
    meaning: "birth; origin",
    description: "Gen means “birth” or “origin.” A generation is all those born in the same period.",
    origin: "Latin/Greek",
    difficulty: "intermediate",
    category: "life",
    mnemonic: "Generate — bring into being.",
    related: ["nat", "bio"],
    words: [
      { word: "generate", definition: "to bring into being", sentence: "The plant generates oxygen." },
      { word: "generation", definition: "those born in the same period", sentence: "The younger generation voted in record numbers." },
      { word: "genesis", definition: "the origin", sentence: "The book describes the genesis of the universe." },
      { word: "indigenous", definition: "born in a place; native", sentence: "The species is indigenous to the island." },
    ],
  },
  {
    text: "grad/gress",
    type: "root",
    meaning: "step; go",
    description: "Grad/gress means “step” or “go.” To graduate is to step up to a degree.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Progress — a step forward.",
    related: ["ced/ceed/cess", "mot/mov/mob"],
    words: [
      { word: "graduate", definition: "to step up to a degree", sentence: "She will graduate in May." },
      { word: "gradual", definition: "step by step", sentence: "Gradual progress is still progress." },
      { word: "progress", definition: "a step forward", sentence: "We made real progress this week." },
      { word: "regress", definition: "to step back", sentence: "Don't regress to old habits." },
      { word: "congress", definition: "a stepping together", sentence: "Congress meets in Washington, D.C." },
    ],
  },
  {
    text: "graph/gram",
    type: "root",
    meaning: "write",
    description: "Graph/gram means “write.” An autograph is a self-writing.",
    origin: "Greek",
    difficulty: "beginner",
    category: "communication",
    mnemonic: "Autograph — written by the self.",
    related: ["scrib/script", "log/logue"],
    words: [
      { word: "autograph", definition: "one's own written name", sentence: "She got his autograph after the game." },
      { word: "telegram", definition: "a message written and sent far", sentence: "They sent a telegram overseas." },
      { word: "diagram", definition: "a drawing that writes out an idea", sentence: "Draw a diagram of the cell." },
      { word: "grammar", definition: "the rules of written language", sentence: "Grammar matters in every essay." },
    ],
  },
  {
    text: "grat",
    type: "root",
    meaning: "pleasing; thankful",
    description: "Grat means “pleasing” or “thankful.” Gratitude is thankfulness.",
    origin: "Latin",
    difficulty: "beginner",
    category: "quality",
    mnemonic: "Grateful — thankful.",
    related: ["bene-/bon-"],
    words: [
      { word: "gratitude", definition: "thankfulness", sentence: "He expressed his gratitude for the gift." },
      { word: "grateful", definition: "thankful", sentence: "We are grateful for your help." },
      { word: "ingrate", definition: "an unthankful person", sentence: "Don't be an ingrate." },
      { word: "congratulate", definition: "to express pleasure with someone", sentence: "We congratulate you on your success." },
    ],
  },
  {
    text: "ject",
    type: "root",
    meaning: "throw",
    description: "Ject means “throw.” To eject is to throw out.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Eject — throw out.",
    related: ["pel/puls"],
    words: [
      { word: "eject", definition: "to throw out", sentence: "The pilot ejected from the plane." },
      { word: "inject", definition: "to throw in", sentence: "The nurse injected the vaccine." },
      { word: "reject", definition: "to throw back", sentence: "They rejected the offer." },
      { word: "project", definition: "to throw forward", sentence: "The project will take a full year." },
      { word: "conjecture", definition: "a throwing together of ideas — a guess", sentence: "It is only a conjecture at this point." },
    ],
  },
  {
    text: "jud/jur/jus",
    type: "root",
    meaning: "law; justice",
    description: "Jud/jur/jus means “law” or “justice.” A judge administers justice.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "mind",
    mnemonic: "Jury — sworn to justice.",
    related: ["cred", "leg"],
    words: [
      { word: "judge", definition: "one who decides by law", sentence: "She was a fair judge." },
      { word: "jury", definition: "a group that judges", sentence: "The jury deliberated for hours." },
      { word: "justice", definition: "fairness by law", sentence: "They demanded justice." },
      { word: "justify", definition: "to show to be right", sentence: "Justify your answer with evidence." },
      { word: "perjury", definition: "lying under law", sentence: "He was charged with perjury." },
    ],
  },
  {
    text: "lect/leg/lig",
    type: "root",
    meaning: "read; choose",
    description: "Lect/leg/lig means “read” or “choose.” To elect is to choose by vote.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "communication",
    mnemonic: "Elect — choose out.",
    related: ["dict", "log/logue"],
    words: [
      { word: "lecture", definition: "a spoken reading to an audience", sentence: "The lecture lasted an hour." },
      { word: "legible", definition: "able to be read", sentence: "His handwriting is legible." },
      { word: "elect", definition: "to choose", sentence: "We elect a president every four years." },
      { word: "select", definition: "to choose out", sentence: "Select your answers carefully." },
      { word: "eligible", definition: "able to be chosen", sentence: "She is eligible for the scholarship." },
      { word: "neglect", definition: "to not choose — to ignore", sentence: "Don't neglect your duties." },
    ],
  },
  {
    text: "log/logue",
    type: "root",
    meaning: "word; speech",
    description: "Log/logue means “word” or “speech.” A dialogue is speech between two people.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "communication",
    mnemonic: "Dialogue — speech between two.",
    related: ["dict", "verb"],
    words: [
      { word: "logic", definition: "reasoning with words", sentence: "The argument lacks logic." },
      { word: "dialogue", definition: "speech between two people", sentence: "The dialogue was witty and sharp." },
      { word: "monologue", definition: "speech by one person", sentence: "The monologue opened the play." },
      { word: "prologue", definition: "speech before the main part", sentence: "The prologue set the scene." },
      { word: "catalog", definition: "a list of words, a listing", sentence: "Browse the online catalog." },
    ],
  },
  {
    text: "luc/lum/lus",
    type: "root",
    meaning: "light",
    description: "Luc/lum/lus means “light.” Lucid means clear, as if lit up.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "perception",
    mnemonic: "Illuminate — shed light on.",
    related: ["vid/vis", "phot"],
    words: [
      { word: "lucid", definition: "clear", sentence: "Her explanation was lucid." },
      { word: "illuminate", definition: "to shed light on", sentence: "The lamp illuminated the room." },
      { word: "translucent", definition: "letting light through", sentence: "The glass was translucent." },
      { word: "luminous", definition: "full of light", sentence: "The moon was luminous." },
      { word: "luster", definition: "shine", sentence: "The metal had a fine luster." },
    ],
  },
  {
    text: "man/manu",
    type: "root",
    meaning: "hand",
    description: "Man/manu means “hand.” Manual work is done by hand.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "body",
    mnemonic: "Manual — by hand.",
    related: ["ped/pod"],
    words: [
      { word: "manual", definition: "done by hand; also, a guidebook", sentence: "Read the manual before assembling it." },
      { word: "manufacture", definition: "to make by hand", sentence: "They manufacture tools in the plant." },
      { word: "manuscript", definition: "a hand-written document", sentence: "The manuscript was finally published." },
      { word: "manipulate", definition: "to handle skillfully", sentence: "He tried to manipulate the data." },
      { word: "emancipate", definition: "to free — literally, to take the hand out", sentence: "The proclamation emancipated the slaves." },
    ],
  },
  {
    text: "mit/miss",
    type: "root",
    meaning: "send",
    description: "Mit/miss means “send.” A mission is a sending forth.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "motion",
    mnemonic: "Mission — a sending.",
    related: ["port", "fer"],
    words: [
      { word: "transmit", definition: "to send across", sentence: "The tower transmits signals." },
      { word: "mission", definition: "a sending forth", sentence: "Her mission was to bring peace." },
      { word: "missile", definition: "something sent through the air", sentence: "The missile was launched." },
      { word: "dismiss", definition: "to send away", sentence: "The teacher dismissed the class." },
      { word: "permit", definition: "to send through — allow", sentence: "The permit allows construction." },
    ],
  },
  {
    text: "mort",
    type: "root",
    meaning: "death",
    description: "Mort means “death.” A mortal is subject to death.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "life",
    mnemonic: "Immortal — not subject to death.",
    related: ["nat", "vit/viv"],
    words: [
      { word: "mortal", definition: "subject to death", sentence: "All humans are mortal." },
      { word: "immortal", definition: "not subject to death", sentence: "The gods were said to be immortal." },
      { word: "mortician", definition: "one who prepares the dead", sentence: "The mortician prepared the body." },
      { word: "mortgage", definition: "literally a “death pledge” on a house", sentence: "They finally paid off the mortgage." },
      { word: "mortify", definition: "to deaden with shame", sentence: "His comment mortified her." },
    ],
  },
  {
    text: "mot/mov/mob",
    type: "root",
    meaning: "move",
    description: "Mot/mov/mob means “move.” Motion is movement.",
    origin: "Latin",
    difficulty: "beginner",
    category: "motion",
    mnemonic: "Motion — movement.",
    related: ["ced/ceed/cess", "grad/gress"],
    words: [
      { word: "motion", definition: "movement", sentence: "The camera captured the motion." },
      { word: "move", definition: "to change position", sentence: "Please move your car." },
      { word: "mobile", definition: "able to move", sentence: "The sculpture was mobile." },
      { word: "motivate", definition: "to move to action", sentence: "The speech motivated the crowd." },
      { word: "emotion", definition: "a moving out of feeling", sentence: "Her emotion showed on her face." },
      { word: "promote", definition: "to move up", sentence: "She was promoted to manager." },
    ],
  },
  {
    text: "nat",
    type: "root",
    meaning: "born",
    description: "Nat means “born.” A native is born in a place.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "life",
    mnemonic: "Native — born there.",
    related: ["gen", "bio"],
    words: [
      { word: "native", definition: "born in a place", sentence: "She is a native of Peru." },
      { word: "nation", definition: "a people born together", sentence: "The nation celebrated its independence." },
      { word: "innate", definition: "born in — natural", sentence: "He has an innate talent for music." },
      { word: "prenatal", definition: "before birth", sentence: "Prenatal care improves outcomes." },
      { word: "renaissance", definition: "a rebirth", sentence: "The Renaissance revived classical art." },
    ],
  },
  {
    text: "nomen/nomin",
    type: "root",
    meaning: "name",
    description: "Nomen/nomin means “name.” To nominate is to name someone for office.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "communication",
    mnemonic: "Nominate — name for office.",
    related: ["log/logue"],
    words: [
      { word: "nominate", definition: "to name for office", sentence: "The party nominated her for mayor." },
      { word: "nominal", definition: "in name only", sentence: "The fee is nominal." },
      { word: "nomenclature", definition: "a system of names", sentence: "Scientific nomenclature uses Latin." },
      { word: "denominator", definition: "the name below the line in a fraction", sentence: "The denominator of 1/2 is 2." },
    ],
  },
];
