import type { SeedWordPart } from "./types";

/** 30 high-utility SAT suffixes with example words. */
export const SUFFIXES: SeedWordPart[] = [
  {
    text: "-able/-ible",
    type: "suffix",
    meaning: "able to be",
    description: "Words ending in -able/-ible describe something that can be done to them.",
    origin: "Latin",
    difficulty: "beginner",
    category: "adjective",
    mnemonic: "Readable — able to be read.",
    related: ["-ive", "-ful"],
    words: [
      { word: "readable", definition: "able to be read", sentence: "The report was clear and readable." },
      { word: "flexible", definition: "able to bend easily", sentence: "The schedule is flexible." },
      { word: "credible", definition: "able to be believed", sentence: "The source was credible." },
      { word: "possible", definition: "able to be done", sentence: "Anything is possible with effort." },
    ],
  },
  {
    text: "-al",
    type: "suffix",
    meaning: "relating to",
    description: "-Al turns nouns into adjectives meaning “relating to.”",
    origin: "Latin",
    difficulty: "beginner",
    category: "adjective",
    mnemonic: "National — relating to a nation.",
    related: ["-ic/-ical", "-ary"],
    words: [
      { word: "national", definition: "relating to a nation", sentence: "The national anthem played." },
      { word: "personal", definition: "relating to a person", sentence: "It was a personal matter." },
      { word: "cultural", definition: "relating to culture", sentence: "The cultural festival drew crowds." },
      { word: "logical", definition: "relating to logic", sentence: "His argument was logical." },
    ],
  },
  {
    text: "-ance/-ence",
    type: "suffix",
    meaning: "state or quality of",
    description: "-ance/-ence turns verbs into nouns naming a state or quality.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Importance — the state of being important.",
    related: ["-ness", "-ity/-ty"],
    words: [
      { word: "importance", definition: "the state of being important", sentence: "The importance of sleep is clear." },
      { word: "difference", definition: "the state of being different", sentence: "The difference was obvious." },
      { word: "confidence", definition: "the state of trusting", sentence: "Her confidence grew." },
      { word: "silence", definition: "the state of being silent", sentence: "Silence fell over the room." },
    ],
  },
  {
    text: "-ant/-ent",
    type: "suffix",
    meaning: "being; one who",
    description: "-ant/-ent describes a state of being or a person who does something.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Student — one who studies.",
    related: ["-ist", "-er/-or"],
    words: [
      { word: "important", definition: "of great significance", sentence: "Time is important." },
      { word: "student", definition: "one who studies", sentence: "The student studied all night." },
      { word: "resident", definition: "one who resides", sentence: "The residents protested the change." },
      { word: "fluent", definition: "flowing smoothly", sentence: "She is fluent in French." },
      { word: "president", definition: "one who sits before — a leader", sentence: "The president addressed the nation." },
    ],
  },
  {
    text: "-ate",
    type: "suffix",
    meaning: "to make; to do",
    description: "-ate turns nouns or adjectives into verbs meaning “to make.”",
    origin: "Latin",
    difficulty: "intermediate",
    category: "verb",
    mnemonic: "Activate — to make active.",
    related: ["-ify", "-ize"],
    words: [
      { word: "activate", definition: "to make active", sentence: "Activate your account online." },
      { word: "educate", definition: "to make educated", sentence: "We must educate the public." },
      { word: "celebrate", definition: "to make festive", sentence: "We celebrate the victory tonight." },
      { word: "motivate", definition: "to make move — inspire", sentence: "The coach motivated the team." },
    ],
  },
  {
    text: "-cide",
    type: "suffix",
    meaning: "kill",
    description: "-cide forms nouns meaning “killer” or “killing.”",
    origin: "Latin",
    difficulty: "advanced",
    category: "noun",
    mnemonic: "Homicide — killing of a person.",
    related: ["cide"],
    words: [
      { word: "homicide", definition: "the killing of a person", sentence: "The detective solved the homicide." },
      { word: "suicide", definition: "the killing of oneself", sentence: "The play addresses suicide honestly." },
      { word: "pesticide", definition: "a killer of pests", sentence: "Farmers use pesticide on crops." },
      { word: "genocide", definition: "the killing of a people", sentence: "The tribunal tried the case as genocide." },
      { word: "insecticide", definition: "a killer of insects", sentence: "Spray the insecticide on the plants." },
    ],
  },
  {
    text: "-cracy",
    type: "suffix",
    meaning: "rule by",
    description: "-cracy forms nouns meaning “rule by” a group or principle.",
    origin: "Greek",
    difficulty: "advanced",
    category: "noun",
    mnemonic: "Democracy — rule by the people.",
    related: ["-archy"],
    words: [
      { word: "democracy", definition: "rule by the people", sentence: "Democracy requires participation." },
      { word: "aristocracy", definition: "rule by the best", sentence: "The aristocracy held power for centuries." },
      { word: "theocracy", definition: "rule by religious authority", sentence: "The country was a theocracy." },
      { word: "bureaucracy", definition: "rule by bureaus and offices", sentence: "The bureaucracy delayed the permit." },
    ],
  },
  {
    text: "-dom",
    type: "suffix",
    meaning: "state; condition",
    description: "-dom forms nouns naming a state, condition, or realm.",
    origin: "Old English",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Freedom — the state of being free.",
    related: ["-hood", "-ship"],
    words: [
      { word: "freedom", definition: "the state of being free", sentence: "They fought for freedom." },
      { word: "kingdom", definition: "the realm of a king", sentence: "The kingdom expanded its borders." },
      { word: "wisdom", definition: "the state of being wise", sentence: "Wisdom comes with age." },
      { word: "boredom", definition: "the state of being bored", sentence: "Boredom set in during the lecture." },
      { word: "martyrdom", definition: "the condition of a martyr", sentence: "He accepted martyrdom for his beliefs." },
    ],
  },
  {
    text: "-ee",
    type: "suffix",
    meaning: "one who receives",
    description: "-ee marks the person who receives the action.",
    origin: "French",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Employee — one who is employed.",
    related: ["-er/-or", "-ant/-ent"],
    words: [
      { word: "employee", definition: "one who is employed", sentence: "The employee was late." },
      { word: "trainee", definition: "one who is trained", sentence: "The trainee practiced all week." },
      { word: "refugee", definition: "one who flees", sentence: "The refugee found shelter." },
      { word: "nominee", definition: "one who is named", sentence: "The nominee accepted the award." },
      { word: "interviewee", definition: "one who is interviewed", sentence: "The interviewee smiled nervously." },
    ],
  },
  {
    text: "-en",
    type: "suffix",
    meaning: "to make",
    description: "-en turns adjectives into verbs meaning “to make.”",
    origin: "Old English",
    difficulty: "intermediate",
    category: "verb",
    mnemonic: "Strengthen — to make strong.",
    related: ["-ify", "-ize"],
    words: [
      { word: "strengthen", definition: "to make strong", sentence: "Exercise strengthens muscles." },
      { word: "sharpen", definition: "to make sharp", sentence: "Sharpen the pencil." },
      { word: "lengthen", definition: "to make longer", sentence: "Lengthen the deadline by a day." },
      { word: "darken", definition: "to make dark", sentence: "The clouds darkened the sky." },
      { word: "wooden", definition: "made of wood", sentence: "The wooden table was sturdy." },
    ],
  },
  {
    text: "-er/-or",
    type: "suffix",
    meaning: "one who does",
    description: "-er/-or marks the person who performs an action.",
    origin: "Latin/Old English",
    difficulty: "beginner",
    category: "noun",
    mnemonic: "Teacher — one who teaches.",
    related: ["-ist", "-ant/-ent"],
    words: [
      { word: "teacher", definition: "one who teaches", sentence: "The teacher explained the lesson." },
      { word: "actor", definition: "one who acts", sentence: "The actor performed brilliantly." },
      { word: "writer", definition: "one who writes", sentence: "The writer published a novel." },
      { word: "inventor", definition: "one who invents", sentence: "The inventor patented the device." },
      { word: "doctor", definition: "one who heals", sentence: "The doctor arrived quickly." },
    ],
  },
  {
    text: "-ful",
    type: "suffix",
    meaning: "full of",
    description: "-ful turns nouns into adjectives meaning “full of.”",
    origin: "Old English",
    difficulty: "beginner",
    category: "adjective",
    mnemonic: "Helpful — full of help.",
    related: ["-less", "-ous/-ose"],
    words: [
      { word: "helpful", definition: "full of help", sentence: "Thank you for the helpful advice." },
      { word: "beautiful", definition: "full of beauty", sentence: "The sunset was beautiful." },
      { word: "careful", definition: "full of care", sentence: "Be careful on the ice." },
      { word: "hopeful", definition: "full of hope", sentence: "She remained hopeful." },
      { word: "powerful", definition: "full of power", sentence: "The speech was powerful." },
    ],
  },
  {
    text: "-fy/-ify",
    type: "suffix",
    meaning: "to make",
    description: "-fy/-ify turns adjectives into verbs meaning “to make.”",
    origin: "Latin",
    difficulty: "intermediate",
    category: "verb",
    mnemonic: "Simplify — to make simple.",
    related: ["-ize", "-en"],
    words: [
      { word: "simplify", definition: "to make simple", sentence: "Simplify the instructions." },
      { word: "beautify", definition: "to make beautiful", sentence: "They beautified the park." },
      { word: "clarify", definition: "to make clear", sentence: "Please clarify your answer." },
      { word: "terrify", definition: "to make afraid", sentence: "The storm terrified the children." },
      { word: "modify", definition: "to make changes", sentence: "Modify the plan as needed." },
    ],
  },
  {
    text: "-hood",
    type: "suffix",
    meaning: "state of being",
    description: "-hood forms nouns naming a state or period of being.",
    origin: "Old English",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Childhood — the state of being a child.",
    related: ["-dom", "-ship"],
    words: [
      { word: "childhood", definition: "the state of being a child", sentence: "Childhood passed quickly." },
      { word: "neighborhood", definition: "the state of being neighbors", sentence: "The neighborhood was quiet." },
      { word: "likelihood", definition: "the state of being likely", sentence: "The likelihood is high." },
      { word: "brotherhood", definition: "the state of being brothers", sentence: "They shared a deep brotherhood." },
      { word: "livelihood", definition: "the means of living", sentence: "Fishing is their livelihood." },
    ],
  },
  {
    text: "-ian",
    type: "suffix",
    meaning: "relating to; one from",
    description: "-ian forms adjectives meaning “relating to” or nouns for people from a field or place.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Musician — one who practices music.",
    related: ["-ist", "-ic/-ical"],
    words: [
      { word: "musician", definition: "one who practices music", sentence: "The musician played for hours." },
      { word: "librarian", definition: "one who keeps a library", sentence: "Ask the librarian for help." },
      { word: "historian", definition: "one who studies history", sentence: "The historian spoke at the museum." },
      { word: "comedian", definition: "one who makes comedy", sentence: "The comedian told jokes." },
      { word: "Parisian", definition: "from Paris", sentence: "The Parisian café charmed us." },
    ],
  },
  {
    text: "-ic/-ical",
    type: "suffix",
    meaning: "relating to",
    description: "-ic/-ical forms adjectives meaning “relating to.”",
    origin: "Greek/Latin",
    difficulty: "intermediate",
    category: "adjective",
    mnemonic: "Poetic — relating to poetry.",
    related: ["-al", "-ary"],
    words: [
      { word: "poetic", definition: "relating to poetry", sentence: "The scene was poetic." },
      { word: "historic", definition: "relating to history", sentence: "The historic building stood for centuries." },
      { word: "logical", definition: "relating to logic", sentence: "The conclusion was logical." },
      { word: "musical", definition: "relating to music", sentence: "She has musical talent." },
      { word: "typical", definition: "relating to a type", sentence: "It was typical behavior for him." },
    ],
  },
  {
    text: "-ing",
    type: "suffix",
    meaning: "action; process",
    description: "-ing forms nouns naming an action or process, and present-tense verbs.",
    origin: "Old English",
    difficulty: "beginner",
    category: "noun",
    mnemonic: "Swimming — the act of swimming.",
    related: ["-tion", "-ment"],
    words: [
      { word: "swimming", definition: "the act of swimming", sentence: "Swimming is good exercise." },
      { word: "teaching", definition: "the act of teaching", sentence: "Teaching is a rewarding career." },
      { word: "building", definition: "the act of building", sentence: "Building takes time and skill." },
      { word: "running", definition: "the act of running", sentence: "Running improves your health." },
      { word: "painting", definition: "the act of painting", sentence: "Painting relaxes her." },
    ],
  },
  {
    text: "-ion/-tion/-sion",
    type: "suffix",
    meaning: "act or state of",
    description: "-ion/-tion/-sion turns verbs into nouns naming an act or state.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Decision — the act of deciding.",
    related: ["-ing", "-ment"],
    words: [
      { word: "decision", definition: "the act of deciding", sentence: "The decision was final." },
      { word: "celebration", definition: "the act of celebrating", sentence: "The celebration lasted all night." },
      { word: "expansion", definition: "the act of expanding", sentence: "The expansion doubled the company's size." },
      { word: "conclusion", definition: "the act of concluding", sentence: "The conclusion followed the evidence." },
      { word: "tension", definition: "the state of being tense", sentence: "Tension filled the room." },
    ],
  },
  {
    text: "-ish",
    type: "suffix",
    meaning: "somewhat like",
    description: "-ish forms adjectives meaning “somewhat like” or “tending to.”",
    origin: "Old English",
    difficulty: "beginner",
    category: "adjective",
    mnemonic: "Childish — like a child.",
    related: ["-ic/-ical", "-ous/-ose"],
    words: [
      { word: "childish", definition: "like a child", sentence: "Stop the childish behavior." },
      { word: "selfish", definition: "caring only for oneself", sentence: "Selfish acts hurt others." },
      { word: "reddish", definition: "somewhat red", sentence: "The light was reddish at dusk." },
      { word: "foolish", definition: "like a fool", sentence: "It was a foolish mistake." },
      { word: "feverish", definition: "somewhat feverous", sentence: "He worked with feverish energy." },
    ],
  },
  {
    text: "-ism",
    type: "suffix",
    meaning: "belief; doctrine",
    description: "-ism forms nouns naming a belief, doctrine, or practice.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Optimism — belief in the good.",
    related: ["-ist"],
    words: [
      { word: "optimism", definition: "belief in the good outcome", sentence: "Her optimism inspired the team." },
      { word: "racism", definition: "belief in racial superiority", sentence: "Racism is unjust and harmful." },
      { word: "heroism", definition: "the practice of heroism", sentence: "Heroism was praised at the ceremony." },
      { word: "capitalism", definition: "an economic belief in free markets", sentence: "Capitalism drives many economies." },
      { word: "feminism", definition: "belief in women's equality", sentence: "Feminism advanced women's rights." },
    ],
  },
  {
    text: "-ist",
    type: "suffix",
    meaning: "one who practices",
    description: "-ist marks a person who practices a field or belief.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Artist — one who practices art.",
    related: ["-ian", "-er/-or"],
    words: [
      { word: "artist", definition: "one who practices art", sentence: "The artist painted daily." },
      { word: "scientist", definition: "one who practices science", sentence: "The scientist ran the experiment." },
      { word: "pianist", definition: "one who plays piano", sentence: "The pianist performed a concerto." },
      { word: "activist", definition: "one who acts for change", sentence: "The activist organized the protest." },
      { word: "journalist", definition: "one who reports the news", sentence: "The journalist asked tough questions." },
    ],
  },
  {
    text: "-ity/-ty",
    type: "suffix",
    meaning: "state; quality",
    description: "-ity/-ty forms nouns naming a state or quality.",
    origin: "Latin",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Ability — the state of being able.",
    related: ["-ance/-ence", "-ness"],
    words: [
      { word: "ability", definition: "the state of being able", sentence: "She has the ability to succeed." },
      { word: "reality", definition: "the state of being real", sentence: "Reality surprised him." },
      { word: "loyalty", definition: "the quality of being loyal", sentence: "Loyalty matters in friendship." },
      { word: "cruelty", definition: "the quality of being cruel", sentence: "Cruelty is inexcusable." },
      { word: "honesty", definition: "the quality of being honest", sentence: "Honesty is the best policy." },
      { word: "safety", definition: "the state of being safe", sentence: "Safety comes first." },
    ],
  },
  {
    text: "-ive",
    type: "suffix",
    meaning: "tending to",
    description: "-ive forms adjectives meaning “tending to.”",
    origin: "Latin",
    difficulty: "intermediate",
    category: "adjective",
    mnemonic: "Creative — tending to create.",
    related: ["-able/-ible", "-ful"],
    words: [
      { word: "creative", definition: "tending to create", sentence: "She is a creative thinker." },
      { word: "active", definition: "tending to act", sentence: "Stay active every day." },
      { word: "expensive", definition: "tending to cost much", sentence: "The meal was expensive." },
      { word: "sensitive", definition: "tending to feel", sentence: "He is sensitive to criticism." },
      { word: "positive", definition: "tending to be good", sentence: "Stay positive." },
    ],
  },
  {
    text: "-ize",
    type: "suffix",
    meaning: "to make; to convert",
    description: "-ize turns nouns or adjectives into verbs meaning “to make” or “to convert.”",
    origin: "Greek/Latin",
    difficulty: "intermediate",
    category: "verb",
    mnemonic: "Realize — to make real in the mind.",
    related: ["-ify", "-ate"],
    words: [
      { word: "realize", definition: "to make real in the mind — understand", sentence: "I realize my mistake now." },
      { word: "organize", definition: "to make organized", sentence: "Organize your notes before the test." },
      { word: "memorize", definition: "to commit to memory", sentence: "Memorize the poem by Friday." },
      { word: "criticize", definition: "to judge", sentence: "Don't criticize unfairly." },
      { word: "modernize", definition: "to make modern", sentence: "They modernized the factory." },
    ],
  },
  {
    text: "-less",
    type: "suffix",
    meaning: "without",
    description: "-less forms adjectives meaning “without.”",
    origin: "Old English",
    difficulty: "beginner",
    category: "adjective",
    mnemonic: "Hopeless — without hope.",
    related: ["-ful"],
    words: [
      { word: "hopeless", definition: "without hope", sentence: "The situation seemed hopeless." },
      { word: "fearless", definition: "without fear", sentence: "She was fearless." },
      { word: "endless", definition: "without end", sentence: "The wait felt endless." },
      { word: "careless", definition: "without care", sentence: "Careless errors cost points." },
      { word: "useless", definition: "without use", sentence: "The tool was useless." },
      { word: "countless", definition: "too many to count", sentence: "Countless stars filled the sky." },
    ],
  },
  {
    text: "-logy",
    type: "suffix",
    meaning: "study of",
    description: "-logy forms nouns naming a field of study.",
    origin: "Greek",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Biology — the study of life.",
    related: ["-ist"],
    words: [
      { word: "biology", definition: "the study of life", sentence: "Biology fascinates her." },
      { word: "psychology", definition: "the study of the mind", sentence: "He studied psychology in college." },
      { word: "geology", definition: "the study of the earth", sentence: "Geology explains how rocks form." },
      { word: "technology", definition: "the study of technique", sentence: "Technology advances quickly." },
      { word: "ecology", definition: "the study of living systems", sentence: "Ecology studies nature's balance." },
    ],
  },
  {
    text: "-ment",
    type: "suffix",
    meaning: "result; action",
    description: "-ment forms nouns naming a result, action, or state.",
    origin: "Latin",
    difficulty: "beginner",
    category: "noun",
    mnemonic: "Government — the result of governing.",
    related: ["-ion/-tion", "-ing"],
    words: [
      { word: "government", definition: "the system of governing", sentence: "The government passed a new law." },
      { word: "movement", definition: "the act of moving", sentence: "The movement grew quickly." },
      { word: "payment", definition: "the act of paying", sentence: "Payment is due on Friday." },
      { word: "achievement", definition: "the act of achieving", sentence: "The achievement was celebrated." },
      { word: "amusement", definition: "the state of being amused", sentence: "The park offered amusement for all." },
    ],
  },
  {
    text: "-ness",
    type: "suffix",
    meaning: "state; quality",
    description: "-ness turns adjectives into nouns naming a state or quality.",
    origin: "Old English",
    difficulty: "beginner",
    category: "noun",
    mnemonic: "Happiness — the state of being happy.",
    related: ["-ance/-ence", "-ity/-ty"],
    words: [
      { word: "happiness", definition: "the state of being happy", sentence: "Money can't buy happiness." },
      { word: "kindness", definition: "the quality of being kind", sentence: "Kindness matters more than wealth." },
      { word: "darkness", definition: "the state of being dark", sentence: "Darkness fell over the valley." },
      { word: "goodness", definition: "the quality of being good", sentence: "Goodness prevailed in the end." },
      { word: "awareness", definition: "the state of knowing", sentence: "Awareness of the issue grew." },
    ],
  },
  {
    text: "-ous/-ose",
    type: "suffix",
    meaning: "full of",
    description: "-ous/-ose forms adjectives meaning “full of.”",
    origin: "Latin",
    difficulty: "intermediate",
    category: "adjective",
    mnemonic: "Dangerous — full of danger.",
    related: ["-ful", "-less"],
    words: [
      { word: "dangerous", definition: "full of danger", sentence: "The path was dangerous." },
      { word: "famous", definition: "full of fame", sentence: "She became famous overnight." },
      { word: "nervous", definition: "full of nerves", sentence: "He felt nervous before the test." },
      { word: "curious", definition: "full of curiosity", sentence: "The child was curious about everything." },
      { word: "vigorous", definition: "full of vigor", sentence: "The debate was vigorous." },
    ],
  },
  {
    text: "-ship",
    type: "suffix",
    meaning: "state; position",
    description: "-ship forms nouns naming a state, condition, or position.",
    origin: "Old English",
    difficulty: "intermediate",
    category: "noun",
    mnemonic: "Friendship — the state of being friends.",
    related: ["-hood", "-dom"],
    words: [
      { word: "friendship", definition: "the state of being friends", sentence: "Their friendship lasted decades." },
      { word: "leadership", definition: "the position of leader", sentence: "Leadership requires trust." },
      { word: "scholarship", definition: "the state of a scholar — a grant", sentence: "She won a full scholarship." },
      { word: "citizenship", definition: "the state of being a citizen", sentence: "Citizenship was granted to her." },
      { word: "ownership", definition: "the state of owning", sentence: "Ownership transferred to the buyer." },
    ],
  },
];
